
gMappy_Settings = {
	["DefaultProfile"] = "NONE",
	["Profiles"] = {
		["gather"] = {
			["Point"] = "TOP",
			["GhostMinimap"] = true,
			["HideZoneName"] = false,
			["MinimapAlpha"] = 0,
			["RelativePoint"] = "TOP",
			["FlashGatherNodes"] = true,
			["HideWorldMap"] = false,
			["UseNormalIcons"] = false,
			["OffsetX"] = 0,
			["HideNorthLabel"] = false,
			["HideZoom"] = false,
			["HideTracking"] = false,
			["AutoArrangeButtons"] = true,
			["MinimapSize"] = 800,
			["StackToScreen"] = true,
			["MinimapCombatAlpha"] = 0,
			["OffsetY"] = 0,
			["HideTimeOfDay"] = false,
			["RotateMinimap"] = true,
		},
		["DEFAULT"] = {
			["Point"] = "TOPRIGHT",
			["LockPosition"] = true,
			["GhostMinimap"] = false,
			["UseNormalIcons"] = false,
			["OffsetY"] = -19.66982449304035,
			["MinimapCombatAlpha"] = 0.2,
			["RelativePoint"] = "TOPRIGHT",
			["MinimapAlpha"] = 1,
			["MinimapSize"] = 241.2940063476563,
			["StackToScreen"] = true,
			["OffsetX"] = -48.83845928746941,
			["StartingCorner"] = "TOPRIGHT",
			["AutoArrangeButtons"] = true,
			["RotateMinimap"] = false,
		},
	},
}
