# -*- coding: utf-8 -*-

from wow_wtf_manager.paths import dir_wotlk_acore_project
from wow_wtf_manager.exp.e03_wotlk.sdm import SDMMacroFile

class Macros:
    sdm_00_common____1001_respawn = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1001-respawn.yml"))
    sdm_00_common____1002_feigh_death = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1002-feigh-death.yml"))
    sdm_00_common____1003_reset_cooldown = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1003-reset-cooldown.yml"))
    sdm_00_common____1004_ice_block = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1004-ice-block.yml"))
    sdm_00_common____1005_resurrection = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1005-resurrection.yml"))
    sdm_00_common____1006_invisibility = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1006-invisibility.yml"))
    sdm_00_common____1007_unbind_instance = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1007-unbind-instance.yml"))
    sdm_00_common____1008_fly_up = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1008-fly-up.yml"))
    sdm_00_common____1009_fly_down = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1009-fly-down.yml"))
    sdm_00_common____1010_x32_speed = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1010-x32-speed.yml"))
    sdm_00_common____1011_MountUp_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1011-MountUp-zhTW.yml"))
    sdm_00_common____1012_MountDown_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1012-MountDown-zhTW.yml"))
    sdm_00_common____1101_target_party = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1101-target-party.yml"))
    sdm_00_common____1102_target_raid = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1102-target-raid.yml"))
    sdm_00_common____1103_target_focus_target = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1103-target-focus-target.yml"))
    sdm_00_common____1104_target_focus_target_target = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1104-target-focus-target-target.yml"))
    sdm_00_common____1105_confirm = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1105-confirm.yml"))
    sdm_00_common____1106_set_focus = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1106-set-focus.yml"))
    sdm_00_common____1107_clear_focus = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1107-clear-focus.yml"))
    sdm_00_common____1108_set_high_fps = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1108-set-high-fps.yml"))
    sdm_00_common____1109_set_low_fps = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1109-set-low-fps.yml"))
    sdm_00_common____1110_follow_focus = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1110-follow-focus.yml"))
    sdm_00_common____1131_target_window_01 = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1131-target-window-01.yml"))
    sdm_00_common____1132_target_window_10 = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1132-target-window-10.yml"))
    sdm_00_common____1151_invite_raid = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1151-invite-raid.yml"))
    sdm_00_common____1152_leave_raid = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1152-leave-raid.yml"))
    sdm_00_common____1153_summon = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1153-summon.yml"))
    sdm_00_common____1171_tele_darnassus = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1171-tele-darnassus.yml"))
    sdm_00_common____1172_tele_ironforge = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1172-tele-ironforge.yml"))
    sdm_00_common____1173_tele_orgrimmar = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1173-tele-orgrimmar.yml"))
    sdm_00_common____1174_tele_undercity = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1174-tele-undercity.yml"))
    sdm_00_common____1175_tele_shattrath = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1175-tele-shattrath.yml"))
    sdm_00_common____1176_tele_dalaran = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1176-tele-dalaran.yml"))
    sdm_00_common____2001_buff_physics_dps = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "2001-buff-physics-dps.yml"))
    sdm_00_common____2002_buff_caster_dps = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "2002-buff-caster-dps.yml"))
    sdm_00_common____2003_buff_tank = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "2003-buff-tank.yml"))
    sdm_00_common____2004_buff_healer = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "2004-buff-healer.yml"))
    sdm_07_druid____0_common____16101_consumable = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "0-common", "16101-consumable.yml"))
    sdm_07_druid____1_balance_resto____16301_buff_self_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "1-balance-resto", "16301-buff-self-zhTW.yml"))
    sdm_07_druid____1_balance_resto____16302_buff_raid_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "1-balance-resto", "16302-buff-raid-zhTW.yml"))
    sdm_07_druid____1_balance_resto____16303_multibox_main_rotate_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "1-balance-resto", "16303-multibox-main-rotate-zhTW.yml"))
    sdm_07_druid____2_resto_and_feral____16501_buff_self_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "2-resto-and-feral", "16501-buff-self-zhTW.yml"))
    sdm_07_druid____2_resto_and_feral____16502_buff_raid_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "2-resto-and-feral", "16502-buff-raid-zhTW.yml"))
    sdm_07_druid____2_resto_and_feral____16503_multibox_main_rotate_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "2-resto-and-feral", "16503-multibox-main-rotate-zhTW.yml"))
    sdm_07_druid____3_feral_and_balance____16701_buff_self_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "3-feral-and-balance", "16701-buff-self-zhTW.yml"))
    sdm_07_druid____3_feral_and_balance____16702_buff_raid_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "3-feral-and-balance", "16702-buff-raid-zhTW.yml"))
    sdm_07_druid____3_feral_and_balance____16703_multibox_main_rotate_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "3-feral-and-balance", "16703-multibox-main-rotate-zhTW.yml"))