# -*- coding: utf-8 -*-

from wow_wtf_manager.paths import dir_wotlk_acore_project
from wow_wtf_manager.exp.e03_wotlk.sdm import SDMMacroFile

class Macros:
    sdm_02_paladin____0_common____11101_consumable = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "0-common", "11101-consumable.yml"))
    sdm_02_paladin____0_common____11111_clear_debuff_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "0-common", "11111-clear-debuff-zhTW.yml"))
    sdm_02_paladin____0_common____11131_protect_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "0-common", "11131-protect-rotation-zhTW.yml"))
    sdm_02_paladin____0_common____11132_retribution_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "0-common", "11132-retribution-rotation-zhTW.yml"))
    sdm_02_paladin____0_common____11133_holy_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "0-common", "11133-holy-rotation-zhTW.yml"))
    sdm_02_paladin____0_common____11151_high_int_heal_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "0-common", "11151-high-int-heal-rotation-zhTW.yml"))
    sdm_02_paladin____0_common____11152_high_crt_heal_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "0-common", "11152-high-crt-heal-rotation-zhTW.yml"))
    sdm_02_paladin____1_protect_retri____11301_act1_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "1-protect-retri", "11301-act1-zhTW.yml"))
    sdm_02_paladin____1_protect_retri____11302_act2_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "1-protect-retri", "11302-act2-zhTW.yml"))
    sdm_02_paladin____1_protect_retri____11303_act3_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "1-protect-retri", "11303-act3-zhTW.yml"))
    sdm_02_paladin____1_protect_retri____11304_act4_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "1-protect-retri", "11304-act4-zhTW.yml"))
    sdm_02_paladin____1_protect_retri____11305_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "1-protect-retri", "11305-rotation-zhTW.yml"))
    sdm_02_paladin____1_protect_retri____11311_buff_self_alliance_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "1-protect-retri", "11311-buff-self-alliance-zhTW.yml"))
    sdm_02_paladin____1_protect_retri____11311_buff_self_horde_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "1-protect-retri", "11311-buff-self-horde-zhTW.yml"))
    sdm_02_paladin____3_holy_protect____11711_act1_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "3-holy-protect", "11711-act1-zhTW.yml"))
    sdm_02_paladin____3_holy_protect____11712_act2_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "3-holy-protect", "11712-act2-zhTW.yml"))
    sdm_02_paladin____3_holy_protect____11731_buff_self_alliance_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "3-holy-protect", "11731-buff-self-alliance-zhTW.yml"))
    sdm_02_paladin____3_holy_protect____11731_buff_self_horde_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "3-holy-protect", "11731-buff-self-horde-zhTW.yml"))
    sdm_02_paladin____3_holy_protect____11751_mb_periodical_beacon_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "3-holy-protect", "11751-mb-periodical-beacon-zhTW.yml"))
    sdm_02_paladin____3_holy_protect____11752_mb_periodical_judgement_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "02-paladin", "3-holy-protect", "11752-mb-periodical-judgement-zhTW.yml"))
    sdm_08_warlock____0_common____18101_consumable = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "08-warlock", "0-common", "18101-consumable.yml"))
    sdm_08_warlock____0_common____18102_elemental_curse_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "08-warlock", "0-common", "18102-elemental-curse-zhTW.yml"))
    sdm_08_warlock____0_common____18103_tongue_curse_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "08-warlock", "0-common", "18103-tongue-curse-zhTW.yml"))
    sdm_08_warlock____0_common____18104_corruption_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "08-warlock", "0-common", "18104-corruption-zhTW.yml"))
    sdm_08_warlock____0_common____18111_demonology_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "08-warlock", "0-common", "18111-demonology-rotation-zhTW.yml"))
    sdm_08_warlock____0_common____18112_affiliation_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "08-warlock", "0-common", "18112-affiliation-rotation-zhTW.yml"))
    sdm_08_warlock____0_common____18113_destruction_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "08-warlock", "0-common", "18113-destruction-rotation-zhTW.yml"))
    sdm_08_warlock____0_common____18114_spell_stone_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "08-warlock", "0-common", "18114-spell-stone-zhTW.yml"))
    sdm_08_warlock____0_common____18115_fire_stone_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "08-warlock", "0-common", "18115-fire-stone-zhTW.yml"))
    sdm_08_warlock____1_demonology_affiliation____18311_burst_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "08-warlock", "1-demonology-affiliation", "18311-burst-zhTW.yml"))
    sdm_08_warlock____1_demonology_affiliation____18321_add_debuff_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "08-warlock", "1-demonology-affiliation", "18321-add-debuff-zhTW.yml"))
    sdm_08_warlock____2_affiliation_destruction____18521_add_debuff_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "08-warlock", "2-affiliation-destruction", "18521-add-debuff-zhTW.yml"))
    sdm_08_warlock____3_destruction_demonology____18721_add_debuff_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "08-warlock", "3-destruction-demonology", "18721-add-debuff-zhTW.yml"))
    sdm_09_mage____0_common____19101_consumable = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "09-mage", "0-common", "19101-consumable.yml"))
    sdm_09_mage____0_common____19102_interrupt_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "09-mage", "0-common", "19102-interrupt-zhTW.yml"))
    sdm_09_mage____0_common____19103_buff_self_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "09-mage", "0-common", "19103-buff-self-zhTW.yml"))
    sdm_09_mage____0_common____19104_buff_team_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "09-mage", "0-common", "19104-buff-team-zhTW.yml"))
    sdm_09_mage____0_common____19105_act3_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "09-mage", "0-common", "19105-act3-zhTW.yml"))
    sdm_09_mage____1_arcane_fire____19311_act1_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "09-mage", "1-arcane-fire", "19311-act1-zhTW.yml"))
    sdm_09_mage____1_arcane_fire____19312_act2_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "09-mage", "1-arcane-fire", "19312-act2-zhTW.yml"))
    sdm_09_mage____1_arcane_fire____19319_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "09-mage", "1-arcane-fire", "19319-rotation-zhTW.yml"))
    sdm_09_mage____1_arcane_fire____19321_burst_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "09-mage", "1-arcane-fire", "19321-burst-zhTW.yml"))
    sdm_09_mage____1_arcane_fire____19322_add_debuff_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "09-mage", "1-arcane-fire", "19322-add-debuff-zhTW.yml"))
    sdm_09_mage____2_fire_frost____19521_burst_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "09-mage", "2-fire-frost", "19521-burst-zhTW.yml"))
    sdm_09_mage____2_fire_frost____19522_add_debuff_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "09-mage", "2-fire-frost", "19522-add-debuff-zhTW.yml"))
    sdm_09_mage____3_frost_arcane____19721_burst_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "09-mage", "3-frost-arcane", "19721-burst-zhTW.yml"))
    sdm_09_mage____3_frost_arcane____19722_add_debuff_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "09-mage", "3-frost-arcane", "19722-add-debuff-zhTW.yml"))
    sdm_10_priest____0_common____19101_consumable = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "10-priest", "0-common", "19101-consumable.yml"))
    sdm_10_priest____0_common____19102_buff_raid_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "10-priest", "0-common", "19102-buff-raid-zhTW.yml"))
    sdm_10_priest____1_shadow_disco____19301_buff_self_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "10-priest", "1-shadow-disco", "19301-buff-self-zhTW.yml"))
    sdm_10_priest____1_shadow_disco____19302_act1_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "10-priest", "1-shadow-disco", "19302-act1-zhTW.yml"))
    sdm_10_priest____1_shadow_disco____19303_act2_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "10-priest", "1-shadow-disco", "19303-act2-zhTW.yml"))
    sdm_10_priest____1_shadow_disco____19306_multibox_main_rotate_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "10-priest", "1-shadow-disco", "19306-multibox-main-rotate-zhTW.yml"))
    sdm_10_priest____2_disco_holy____19501_buff_self_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "10-priest", "2-disco-holy", "19501-buff-self-zhTW.yml"))
    sdm_10_priest____2_disco_holy____19521_heal_rotate_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "10-priest", "2-disco-holy", "19521-heal-rotate-zhTW.yml"))
    sdm_10_priest____2_disco_holy____19522_mb_periodical_prayer_of_mending_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "10-priest", "2-disco-holy", "19522-mb-periodical-prayer-of-mending-zhTW.yml"))
    sdm_10_priest____3_holy_shadow____19701_buff_self_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "10-priest", "3-holy-shadow", "19701-buff-self-zhTW.yml"))
    sdm_03_dk____0_common____13101_consumable = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "03-dk", "0-common", "13101-consumable.yml"))
    sdm_03_dk____0_common____13111_act1_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "03-dk", "0-common", "13111-act1-zhTW.yml"))
    sdm_03_dk____0_common____13112_act2_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "03-dk", "0-common", "13112-act2-zhTW.yml"))
    sdm_03_dk____0_common____13113_act3_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "03-dk", "0-common", "13113-act3-zhTW.yml"))
    sdm_03_dk____0_common____13114_act4_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "03-dk", "0-common", "13114-act4-zhTW.yml"))
    sdm_03_dk____0_common____13121_blood_buff_self_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "03-dk", "0-common", "13121-blood-buff-self-zhTW.yml"))
    sdm_03_dk____0_common____13122_unholy_buff_self_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "03-dk", "0-common", "13122-unholy-buff-self-zhTW.yml"))
    sdm_03_dk____0_common____13123_frost_buff_self_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "03-dk", "0-common", "13123-frost-buff-self-zhTW.yml"))
    sdm_03_dk____0_common____13131_tank_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "03-dk", "0-common", "13131-tank-rotation-zhTW.yml"))
    sdm_03_dk____0_common____13132_tank_survival_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "03-dk", "0-common", "13132-tank-survival-rotation-zhTW.yml"))
    sdm_00_common____1001_respawn = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1001-respawn.yml"))
    sdm_00_common____1002_feigh_death = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1002-feigh-death.yml"))
    sdm_00_common____1003_reset_cooldown = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1003-reset-cooldown.yml"))
    sdm_00_common____1004_ice_block = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1004-ice-block.yml"))
    sdm_00_common____1005_resurrection = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1005-resurrection.yml"))
    sdm_00_common____1006_invisibility = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1006-invisibility.yml"))
    sdm_00_common____1007_unbind_instance = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1007-unbind-instance.yml"))
    sdm_00_common____1008_fly_up = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1008-fly-up.yml"))
    sdm_00_common____1009_fly_down = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1009-fly-down.yml"))
    sdm_00_common____1010_x32_speed = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1010-x32-speed.yml"))
    sdm_00_common____1011_MountUp_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1011-MountUp-zhTW.yml"))
    sdm_00_common____1012_MountDown_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1012-MountDown-zhTW.yml"))
    sdm_00_common____1101_target_party = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1101-target-party.yml"))
    sdm_00_common____1102_target_raid = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1102-target-raid.yml"))
    sdm_00_common____1103_target_focus_target = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1103-target-focus-target.yml"))
    sdm_00_common____1104_target_focus_target_target = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1104-target-focus-target-target.yml"))
    sdm_00_common____1105_confirm = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1105-confirm.yml"))
    sdm_00_common____1106_set_focus = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1106-set-focus.yml"))
    sdm_00_common____1107_clear_focus = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1107-clear-focus.yml"))
    sdm_00_common____1108_set_high_fps = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1108-set-high-fps.yml"))
    sdm_00_common____1109_set_low_fps = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1109-set-low-fps.yml"))
    sdm_00_common____1110_follow_focus = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1110-follow-focus.yml"))
    sdm_00_common____1131_target_window_01 = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1131-target-window-01.yml"))
    sdm_00_common____1132_target_window_10 = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1132-target-window-10.yml"))
    sdm_00_common____1151_invite_raid = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1151-invite-raid.yml"))
    sdm_00_common____1152_leave_raid = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1152-leave-raid.yml"))
    sdm_00_common____1153_summon = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1153-summon.yml"))
    sdm_00_common____1171_tele_darnassus = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1171-tele-darnassus.yml"))
    sdm_00_common____1172_tele_ironforge = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1172-tele-ironforge.yml"))
    sdm_00_common____1173_tele_orgrimmar = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1173-tele-orgrimmar.yml"))
    sdm_00_common____1174_tele_undercity = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1174-tele-undercity.yml"))
    sdm_00_common____1175_tele_shattrath = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1175-tele-shattrath.yml"))
    sdm_00_common____1176_tele_dalaran = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "1176-tele-dalaran.yml"))
    sdm_00_common____2001_buff_physics_dps = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "2001-buff-physics-dps.yml"))
    sdm_00_common____2002_buff_caster_dps = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "2002-buff-caster-dps.yml"))
    sdm_00_common____2003_buff_tank = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "2003-buff-tank.yml"))
    sdm_00_common____2004_buff_healer = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "2004-buff-healer.yml"))
    sdm_00_common____6001_mb_special1 = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "6001-mb-special1.yml"))
    sdm_00_common____6002_mb_special2 = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "6002-mb-special2.yml"))
    sdm_00_common____6003_mb_special3 = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "00-common", "6003-mb-special3.yml"))
    sdm_04_hunter____0_common____14101_consumable = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "04-hunter", "0-common", "14101-consumable.yml"))
    sdm_04_hunter____0_common____14102_misdirect_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "04-hunter", "0-common", "14102-misdirect-zhTW.yml"))
    sdm_04_hunter____0_common____14103_tranquil_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "04-hunter", "0-common", "14103-tranquil-zhTW.yml"))
    sdm_04_hunter____0_common____14104_pack_aspect_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "04-hunter", "0-common", "14104-pack-aspect-zhTW.yml"))
    sdm_04_hunter____0_common____14105_viper_aspect_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "04-hunter", "0-common", "14105-viper-aspect-zhTW.yml"))
    sdm_04_hunter____0_common____14106_burst_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "04-hunter", "0-common", "14106-burst-zhTW.yml"))
    sdm_04_hunter____0_common____14111_act1_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "04-hunter", "0-common", "14111-act1-zhTW.yml"))
    sdm_04_hunter____0_common____14121_marksmanship_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "04-hunter", "0-common", "14121-marksmanship-rotation-zhTW.yml"))
    sdm_04_hunter____0_common____14122_survival_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "04-hunter", "0-common", "14122-survival-rotation-zhTW.yml"))
    sdm_04_hunter____0_common____14123_beast_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "04-hunter", "0-common", "14123-beast-rotation-zhTW.yml"))
    sdm_04_hunter____1_marksmanship_survival____14301_buff_self_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "04-hunter", "1-marksmanship-survival", "14301-buff-self-zhTW.yml"))
    sdm_04_hunter____1_marksmanship_survival____14312_act2_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "04-hunter", "1-marksmanship-survival", "14312-act2-zhTW.yml"))
    sdm_04_hunter____1_marksmanship_survival____14313_act3_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "04-hunter", "1-marksmanship-survival", "14313-act3-zhTW.yml"))
    sdm_04_hunter____1_marksmanship_survival____14314_act4_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "04-hunter", "1-marksmanship-survival", "14314-act4-zhTW.yml"))
    sdm_04_hunter____1_marksmanship_survival____14321_add_debuff_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "04-hunter", "1-marksmanship-survival", "14321-add-debuff-zhTW.yml"))
    sdm_07_druid____0_common____17101_consumable = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "0-common", "17101-consumable.yml"))
    sdm_07_druid____1_balance_resto____17301_buff_self_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "1-balance-resto", "17301-buff-self-zhTW.yml"))
    sdm_07_druid____1_balance_resto____17302_buff_raid_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "1-balance-resto", "17302-buff-raid-zhTW.yml"))
    sdm_07_druid____1_balance_resto____17303_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "1-balance-resto", "17303-rotation-zhTW.yml"))
    sdm_07_druid____2_resto_and_feral____17501_buff_self_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "2-resto-and-feral", "17501-buff-self-zhTW.yml"))
    sdm_07_druid____2_resto_and_feral____17502_buff_raid_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "2-resto-and-feral", "17502-buff-raid-zhTW.yml"))
    sdm_07_druid____2_resto_and_feral____17503_multibox_main_rotate_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "2-resto-and-feral", "17503-multibox-main-rotate-zhTW.yml"))
    sdm_07_druid____2_resto_and_feral____17504_multibox_slow_heal_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "2-resto-and-feral", "17504-multibox-slow-heal-zhTW.yml"))
    sdm_07_druid____3_feral_and_balance____17701_buff_self_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "3-feral-and-balance", "17701-buff-self-zhTW.yml"))
    sdm_07_druid____3_feral_and_balance____17702_buff_raid_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "3-feral-and-balance", "17702-buff-raid-zhTW.yml"))
    sdm_07_druid____3_feral_and_balance____17703_multibox_main_rotate_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "3-feral-and-balance", "17703-multibox-main-rotate-zhTW.yml"))
    sdm_07_druid____1_balance_resto____6001_MB_Special1_ICC_1_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "1-balance-resto", "6001-MB-Special1-ICC-1-zhTW.yml"))
    sdm_07_druid____1_balance_resto____6001_MB_Special1_ICC_4_1st_blow_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "1-balance-resto", "6001-MB-Special1-ICC-4-1st-blow-zhTW.yml"))
    sdm_07_druid____1_balance_resto____6001_MB_Special1_ICC_4_2st_blow_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "1-balance-resto", "6001-MB-Special1-ICC-4-2st-blow-zhTW.yml"))
    sdm_07_druid____1_balance_resto____6001_MB_Special1_ICC_4_3st_blow_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "1-balance-resto", "6001-MB-Special1-ICC-4-3st-blow-zhTW.yml"))
    sdm_07_druid____1_balance_resto____6001_MB_Special1_ICC_4_4st_blow_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "07-druid", "1-balance-resto", "6001-MB-Special1-ICC-4-4st-blow-zhTW.yml"))
    sdm_05_shaman____0_common____15101_consumable = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "05-shaman", "0-common", "15101-consumable.yml"))
    sdm_05_shaman____0_common____15102_interrupt = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "05-shaman", "0-common", "15102-interrupt.yml"))
    sdm_05_shaman____0_common____15111_elemental_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "05-shaman", "0-common", "15111-elemental-rotation-zhTW.yml"))
    sdm_05_shaman____0_common____15112_resto_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "05-shaman", "0-common", "15112-resto-rotation-zhTW.yml"))
    sdm_05_shaman____0_common____15113_enhancement_rotation_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "05-shaman", "0-common", "15113-enhancement-rotation-zhTW.yml"))
    sdm_05_shaman____0_common____15114_mb_resto_earth_shield_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "05-shaman", "0-common", "15114-mb-resto-earth-shield-zhTW.yml"))
    sdm_05_shaman____1_elemental_resto____15311_buff_self_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "05-shaman", "1-elemental-resto", "15311-buff-self-zhTW.yml"))
    sdm_05_shaman____1_elemental_resto____15312_burst_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "05-shaman", "1-elemental-resto", "15312-burst-zhTW.yml"))
    sdm_05_shaman____2_resto_enhancement____15511_buff_self_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "05-shaman", "2-resto-enhancement", "15511-buff-self-zhTW.yml"))
    sdm_05_shaman____2_resto_enhancement____15512_burst_zhTW = SDMMacroFile(path=dir_wotlk_acore_project.joinpath("SuperDuperMacro", "05-shaman", "2-resto-enhancement", "15512-burst-zhTW.yml"))